# Generated by Django 3.0.5 on 2020-04-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
